name: 3 Tier Architecture Provision

on:
  push:
    branches:
      # - main
      - dev
      - devops-barney
  
  pull_request:
    branches:
      # - main
      - dev
      - devops-barney

env:
  AWS_REGION: "ap-southeast-2"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  apply:
    name: "Provision 3 tier architecture on aws"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./root
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      
      - name: Tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          soft_fail: true
      
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Terraform Init
        run: terraform init -input=false -reconfigure -backend-config="backend_dev.config"
      
      - name: Terraform Format
        run:  terraform fmt -check
      
      - name: Terraform Validate
        run: terraform validate
      
      - name: Terraform Plan
        run: terraform plan -input=false -var-file='dev.tfvars' -out=planfile
      
      - name: Terraform Apply
        if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false planfile
      